[build-system]

requires = 
["setuptools>=61.0"] 




build-backend = "setuptools.build_meta"

[project]
name = "SPI2Py"
version = "0.0.1"
authors = [
  { name="Chad Peterson", email="cp44@illinois.edu" },
]
description = "Spatial packaging of interconnected systems with physical interactions"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
"scipy~=1.9.0", 
"networkx~=2.8.5", 
"matplotlib==3.5.3", 
"PyYAML~=6.0",
"numpy<=1.22.4",
"numba>=0.56.0",
"imageio>=2.21.1",
"pytest",
"sphinx",
"cypari~=2.4.1"
]

[tool.pytest.ini_options]
pythonpath = [
  ".","src/","src/SPI2Py/","src/SPI2Py/utils/",
]

[project.urls]
"Homepage" = "https://github.com/SPI2Py/SPI2Py"
"Bug Tracker" = "https://github.com/SPI2Py/SPI2Py/issues"